/*
 * This file is generated by jOOQ.
 */
package ru.vityaman.itmo.web.lab.taparia.storage.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import ru.vityaman.itmo.web.lab.taparia.storage.jooq.Taparia;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PermissionUserPictureType implements EnumType {

    READ("READ"),

    DELETE("DELETE");

    private final String literal;

    private PermissionUserPictureType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Taparia.TAPARIA;
    }

    @Override
    public String getName() {
        return "permission_user_picture_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static PermissionUserPictureType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(PermissionUserPictureType.class, literal);
    }
}
