/*
 * This file is generated by jOOQ.
 */
package ru.vityaman.itmo.web.lab.taparia.storage.jooq;


import ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables.AccessToken;
import ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables.PermissionUserPicture;
import ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables.Picture;
import ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables.TapResult;
import ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables.UserAccount;


/**
 * Convenience access to all tables in taparia.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>taparia.access_token</code>.
     */
    public static final AccessToken ACCESS_TOKEN = AccessToken.ACCESS_TOKEN;

    /**
     * The table <code>taparia.permission_user_picture</code>.
     */
    public static final PermissionUserPicture PERMISSION_USER_PICTURE = PermissionUserPicture.PERMISSION_USER_PICTURE;

    /**
     * The table <code>taparia.picture</code>.
     */
    public static final Picture PICTURE = Picture.PICTURE;

    /**
     * The table <code>taparia.tap_result</code>.
     */
    public static final TapResult TAP_RESULT = TapResult.TAP_RESULT;

    /**
     * The table <code>taparia.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;
}
