/*
 * This file is generated by jOOQ.
 */
package ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.YearToSecond;

import ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables.AccessToken;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccessTokenRecord extends UpdatableRecordImpl<AccessTokenRecord> implements Record4<Long, String, LocalDateTime, YearToSecond> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>taparia.access_token.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>taparia.access_token.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>taparia.access_token.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>taparia.access_token.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>taparia.access_token.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>taparia.access_token.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>taparia.access_token.ttl</code>.
     */
    public void setTtl(YearToSecond value) {
        set(3, value);
    }

    /**
     * Getter for <code>taparia.access_token.ttl</code>.
     */
    public YearToSecond getTtl() {
        return (YearToSecond) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, LocalDateTime, YearToSecond> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, LocalDateTime, YearToSecond> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AccessToken.ACCESS_TOKEN.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return AccessToken.ACCESS_TOKEN.TOKEN;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return AccessToken.ACCESS_TOKEN.CREATED_AT;
    }

    @Override
    public Field<YearToSecond> field4() {
        return AccessToken.ACCESS_TOKEN.TTL;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getToken();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public YearToSecond component4() {
        return getTtl();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getToken();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public YearToSecond value4() {
        return getTtl();
    }

    @Override
    public AccessTokenRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public AccessTokenRecord value2(String value) {
        setToken(value);
        return this;
    }

    @Override
    public AccessTokenRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AccessTokenRecord value4(YearToSecond value) {
        setTtl(value);
        return this;
    }

    @Override
    public AccessTokenRecord values(Long value1, String value2, LocalDateTime value3, YearToSecond value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccessTokenRecord
     */
    public AccessTokenRecord() {
        super(AccessToken.ACCESS_TOKEN);
    }

    /**
     * Create a detached, initialised AccessTokenRecord
     */
    public AccessTokenRecord(Long userId, String token, LocalDateTime createdAt, YearToSecond ttl) {
        super(AccessToken.ACCESS_TOKEN);

        setUserId(userId);
        setToken(token);
        setCreatedAt(createdAt);
        setTtl(ttl);
    }
}
