/*
 * This file is generated by jOOQ.
 */
package ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.vityaman.itmo.web.lab.taparia.storage.jooq.enums.TapResultStatus;
import ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables.TapResult;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TapResultRecord extends UpdatableRecordImpl<TapResultRecord> implements Record6<Long, Long, Long, Long, Long, TapResultStatus> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>taparia.tap_result.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>taparia.tap_result.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>taparia.tap_result.owner_id</code>.
     */
    public void setOwnerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>taparia.tap_result.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>taparia.tap_result.picture_id</code>.
     */
    public void setPictureId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>taparia.tap_result.picture_id</code>.
     */
    public Long getPictureId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>taparia.tap_result.x</code>.
     */
    public void setX(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>taparia.tap_result.x</code>.
     */
    public Long getX() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>taparia.tap_result.y</code>.
     */
    public void setY(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>taparia.tap_result.y</code>.
     */
    public Long getY() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>taparia.tap_result.status</code>.
     */
    public void setStatus(TapResultStatus value) {
        set(5, value);
    }

    /**
     * Getter for <code>taparia.tap_result.status</code>.
     */
    public TapResultStatus getStatus() {
        return (TapResultStatus) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, Long, TapResultStatus> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Long, Long, TapResultStatus> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TapResult.TAP_RESULT.ID;
    }

    @Override
    public Field<Long> field2() {
        return TapResult.TAP_RESULT.OWNER_ID;
    }

    @Override
    public Field<Long> field3() {
        return TapResult.TAP_RESULT.PICTURE_ID;
    }

    @Override
    public Field<Long> field4() {
        return TapResult.TAP_RESULT.X;
    }

    @Override
    public Field<Long> field5() {
        return TapResult.TAP_RESULT.Y;
    }

    @Override
    public Field<TapResultStatus> field6() {
        return TapResult.TAP_RESULT.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOwnerId();
    }

    @Override
    public Long component3() {
        return getPictureId();
    }

    @Override
    public Long component4() {
        return getX();
    }

    @Override
    public Long component5() {
        return getY();
    }

    @Override
    public TapResultStatus component6() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOwnerId();
    }

    @Override
    public Long value3() {
        return getPictureId();
    }

    @Override
    public Long value4() {
        return getX();
    }

    @Override
    public Long value5() {
        return getY();
    }

    @Override
    public TapResultStatus value6() {
        return getStatus();
    }

    @Override
    public TapResultRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TapResultRecord value2(Long value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public TapResultRecord value3(Long value) {
        setPictureId(value);
        return this;
    }

    @Override
    public TapResultRecord value4(Long value) {
        setX(value);
        return this;
    }

    @Override
    public TapResultRecord value5(Long value) {
        setY(value);
        return this;
    }

    @Override
    public TapResultRecord value6(TapResultStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public TapResultRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, TapResultStatus value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TapResultRecord
     */
    public TapResultRecord() {
        super(TapResult.TAP_RESULT);
    }

    /**
     * Create a detached, initialised TapResultRecord
     */
    public TapResultRecord(Long id, Long ownerId, Long pictureId, Long x, Long y, TapResultStatus status) {
        super(TapResult.TAP_RESULT);

        setId(id);
        setOwnerId(ownerId);
        setPictureId(pictureId);
        setX(x);
        setY(y);
        setStatus(status);
    }
}
