/*
 * This file is generated by jOOQ.
 */
package ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.vityaman.itmo.web.lab.taparia.storage.jooq.Keys;
import ru.vityaman.itmo.web.lab.taparia.storage.jooq.Taparia;
import ru.vityaman.itmo.web.lab.taparia.storage.jooq.enums.PermissionUserPictureType;
import ru.vityaman.itmo.web.lab.taparia.storage.jooq.tables.records.PermissionUserPictureRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionUserPicture extends TableImpl<PermissionUserPictureRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>taparia.permission_user_picture</code>
     */
    public static final PermissionUserPicture PERMISSION_USER_PICTURE = new PermissionUserPicture();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PermissionUserPictureRecord> getRecordType() {
        return PermissionUserPictureRecord.class;
    }

    /**
     * The column <code>taparia.permission_user_picture.owner_id</code>.
     */
    public final TableField<PermissionUserPictureRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>taparia.permission_user_picture.type</code>.
     */
    public final TableField<PermissionUserPictureRecord, PermissionUserPictureType> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(ru.vityaman.itmo.web.lab.taparia.storage.jooq.enums.PermissionUserPictureType.class), this, "");

    /**
     * The column <code>taparia.permission_user_picture.picture_id</code>.
     */
    public final TableField<PermissionUserPictureRecord, Long> PICTURE_ID = createField(DSL.name("picture_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private PermissionUserPicture(Name alias, Table<PermissionUserPictureRecord> aliased) {
        this(alias, aliased, null);
    }

    private PermissionUserPicture(Name alias, Table<PermissionUserPictureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>taparia.permission_user_picture</code> table
     * reference
     */
    public PermissionUserPicture(String alias) {
        this(DSL.name(alias), PERMISSION_USER_PICTURE);
    }

    /**
     * Create an aliased <code>taparia.permission_user_picture</code> table
     * reference
     */
    public PermissionUserPicture(Name alias) {
        this(alias, PERMISSION_USER_PICTURE);
    }

    /**
     * Create a <code>taparia.permission_user_picture</code> table reference
     */
    public PermissionUserPicture() {
        this(DSL.name("permission_user_picture"), null);
    }

    public <O extends Record> PermissionUserPicture(Table<O> child, ForeignKey<O, PermissionUserPictureRecord> key) {
        super(child, key, PERMISSION_USER_PICTURE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Taparia.TAPARIA;
    }

    @Override
    public UniqueKey<PermissionUserPictureRecord> getPrimaryKey() {
        return Keys.PERMISSION_USER_PICTURE_PKEY;
    }

    @Override
    public List<ForeignKey<PermissionUserPictureRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PERMISSION_USER_PICTURE__FK_USER_ACCOUNT, Keys.PERMISSION_USER_PICTURE__FK_PICTURE);
    }

    private transient UserAccount _userAccount;
    private transient Picture _picture;

    /**
     * Get the implicit join path to the <code>taparia.user_account</code>
     * table.
     */
    public UserAccount userAccount() {
        if (_userAccount == null)
            _userAccount = new UserAccount(this, Keys.PERMISSION_USER_PICTURE__FK_USER_ACCOUNT);

        return _userAccount;
    }

    /**
     * Get the implicit join path to the <code>taparia.picture</code> table.
     */
    public Picture picture() {
        if (_picture == null)
            _picture = new Picture(this, Keys.PERMISSION_USER_PICTURE__FK_PICTURE);

        return _picture;
    }

    @Override
    public PermissionUserPicture as(String alias) {
        return new PermissionUserPicture(DSL.name(alias), this);
    }

    @Override
    public PermissionUserPicture as(Name alias) {
        return new PermissionUserPicture(alias, this);
    }

    @Override
    public PermissionUserPicture as(Table<?> alias) {
        return new PermissionUserPicture(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PermissionUserPicture rename(String name) {
        return new PermissionUserPicture(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PermissionUserPicture rename(Name name) {
        return new PermissionUserPicture(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PermissionUserPicture rename(Table<?> name) {
        return new PermissionUserPicture(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, PermissionUserPictureType, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super PermissionUserPictureType, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super PermissionUserPictureType, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
